name: stock-prediction
region: sgp1
services:
- name: backend
  dockerfile_path: Dockerfile
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: qthai2210/stock-prediction
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
- name: frontend
  dockerfile_path: Dockerfile.frontend
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
    repo: qthai2210/stock-prediction
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: ${backend.PUBLIC_URL}
